### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by parvez11111** [noob-hackers/sneakphish#1]
-e \e[90m

\e[90m      ███████\e[92m╗\e[90m███\e[92m╗   \e[90m██\e[92m╗\e[90m███████\e[92m╗ \e[90m█████\e[92m╗ \e[90m██\e[92m╗  \e[90m██\e[92m╗            \e[90m      ██\e[92m╔════╝\e[90m████\e[92m╗  \e[90m██\e[92m║\e[90m██\e[92m╔════╝\e[90m██\e[92m╔══\e[90m██\e[92m╗\e[90m██\e[92m║ \e[90m██\e[92m╔╝
\e[90m      ███████\e[92m╗\e[90m██\e[92m╔\e[90m██\e[92m╗ \e[90m██\e[92m║\e[90m█████\e[92m╗  \e[90m███████\e[92m║\e[90m█████\e[92m╔╝             \e[92m      ╚════\e[90m██\e[92m║\e[90m██\e[92m║╚\e[90m██\e[92m╗\e[90m██\e[92m║\e[90m██\e[92m╔══╝  \e[90m██\e[92m╔══\e[90m██\e[92m║\e[90m██\e[92m╔═\e[90m██\e[92m╗                               \e[90m      ███████\e[92m║\e[90m██\e[92m║ ╚\e[90m████\e[92m║\e[90m███████\e[92m╗\e[90m██\e[92m║  \e[90m██\e[92m║\e[90m██\e[92m║  \e[90m██\e[92m╗
\e[92m      ╚══════╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═\e[92m╝
-e \e[34m
\e[34m         ██████╗ ██╗  ██╗██╗███████╗██╗  ██╗
\e[34m         ██╔══██╗██║  ██║██║██╔════╝██║  ██║
\e[34m         ██████╔╝███████║██║███████╗███████║
\e[34m         ██\e[90m╔═══╝ \e[34m██\e[90m╔══\e[34m██\e[90m║\e[34m██\e[90m║\e[90m╚════\e[34m██\e[90m║\e[34m██\e[90m╔══\e[34m██\e[90m║
\e[34m         ██\e[90m║     \e[34m██\e[90m║  \e[34m██\e[90m║\e[34m██\e[90m║\e[34m███████\e[90m║\e[34m██\e[90m║  \e[34m██\e[90m║
\e[90m         ╚═╝     ╚═╝  ╚═╝╚═╝╚══════╝╚═╝  ╚═╝

-e               \e[92m::~:: \e[0mBY NOOB HACKERS\e[92m ::~::\e[0m
-e          \e[92m::~:: \e[0mgithub.com/noob-hackers\e[92m ::~::\e[0m

-e                     \e[92m[\e[34m1\e[92m]\e[92m---\e[92mSTART\e[0m
-e                     \e[92m[\e[34m2\e[92m]\e[92m---\e[92mUPDATE\e[0m
-e                     \e[92m[\e[34m3\e[92m]\e[92m---\e[92mABOUT\e[0m
-e                     \e[92m[\e[34m4\e[92m]\e[92m---\e[92mMORE\e[0m
-e                     \e[92m[\e[34m5\e[92m]\e[92m---\e[92mFOLLOW\e[0m
-e                     \e[92m[\e[34m6\e[92m]\e[92m---\e[92mVIDEO\e[0m
-e                     \e[92m[\e[34m7\e[92m]\e[92m---\e[92mCHAT NOW\e[0m
-e                     \e[92m[\e[34m8\e[92m]\e[92m---\e[92mRESTART\e[0m
-e                     \e[92m[\e[34m9\e[92m]\e[92m---\e[92mEXIT\e[0m

-ne \e[92mSelect Option\e[0m: \e[92m
start
sneakphish.sh: 72: [[: not found
sneakphish.sh: 472: [[: not found
sneakphish.sh: 476: [[: not found
sneakphish.sh: 480: [[: not found

\e[1;92m[\e[34m•\e[1;92m] Downloading Ngrok...
sneakphish.sh: 486: [[: not found
sneakphish.sh: 500: [[: not found

**Comment by halfstackpgr** [comment]
can you get me a log of it ?

**Comment by halfstackpgr** [comment]
And yes could you please tell me how to reproduce the problem ? 
What steps did you follow .
